void exception_entry(void);